### PR TITLE
chore: fix webpack on windows and hmr config

### PR DESCRIPTION
**Pull request by wclr**
fixes:
https://github.com/cyclejs-community/xstream-boilerplate/issues/13
https://github.com/cyclejs-community/xstream-boilerplate/issues/12

### CODE REVIEW

**Comment by TylorS** [comment]
Hey, sorry, I just turned on circleci builds for this repo (They still pointed to TylorS/xstream-boilerplate), could you please refresh this so it runs the builds?

I think there are some trailing spaces in the .babelrc that could be removed :)

Sorry!

**Comment by wclr** [comment]
`npm run lint` tells nothing

**Comment by TylorS** [comment]
Yeah `npm run lint` only checks code in `src/`, it was just a simple suggestion to 'refresh' the PR.

The circleci build is failing, but I really don't think its issues here. Coveralls reporting doesn't seem to work unless the script is run by me :/ I need to figure that out later. Gonna merge

LGTM

**Comment by TylorS** [comment]
Thank you!

**Comment by wclr** [comment]
you could to spread linting on config files .babelrc and webpack.config

**Pull request merged**
