### PR TITLE
test(ComponentRouter): lengthen the timeout of tests

### LINKED ISSUE #179: Support XStream v6.3+
We should support xstream v6.3+ as it has Observable interop which is super awesome.

### PR DESCRIPTION
**Pull request by TylorS**
@FeliciousX I'm making a crappy attempt here, but it's only wild guesses. But here we can maybe try to work out what's going on.

Closes #179

### CODE REVIEW

**Comment by TylorS** [comment]
@FeliciousX this actually worked. Merge if you're okay with it :)

**Comment by FeliciousX** [comment]
@TylorS u forgot to first update to xstream :P

**Comment by TylorS** [comment]
Haha my bad. I'm an idiot at 2am 😊

**Comment by TylorS** [comment]
@FeliciousX I think I found a solution to the tests

**Comment by FeliciousX** [comment]
awesome !! :D

**Pull request merged**
